// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3cXNY18G_b4H7kI2oJ4Jkas_IOrPp6BU',
    appId: '1:258011664234:web:c4a9af83d34d3928839f13',
    messagingSenderId: '258011664234',
    projectId: 'projecto-mango',
    authDomain: 'projecto-mango.firebaseapp.com',
    storageBucket: 'projecto-mango.appspot.com',
    measurementId: 'G-92VBZPKEGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCHcEsl1NVNNuq14Tq-qcfmYBMOWPc4k',
    appId: '1:258011664234:android:5fa41646dc05a37d839f13',
    messagingSenderId: '258011664234',
    projectId: 'projecto-mango',
    storageBucket: 'projecto-mango.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6zmp5sTCQCKTjkZSWMsIaWfuJ8S03DOs',
    appId: '1:258011664234:ios:9770919266ac385b839f13',
    messagingSenderId: '258011664234',
    projectId: 'projecto-mango',
    storageBucket: 'projecto-mango.appspot.com',
    androidClientId: '258011664234-55aktgdjgqt8k3r9grce8trebsu0h24o.apps.googleusercontent.com',
    iosClientId: '258011664234-tvdop8vk9tucashgkkvpu1sc81fst8af.apps.googleusercontent.com',
    iosBundleId: 'cl.pulpox.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6zmp5sTCQCKTjkZSWMsIaWfuJ8S03DOs',
    appId: '1:258011664234:ios:e1b57a06686955db839f13',
    messagingSenderId: '258011664234',
    projectId: 'projecto-mango',
    storageBucket: 'projecto-mango.appspot.com',
    androidClientId: '258011664234-55aktgdjgqt8k3r9grce8trebsu0h24o.apps.googleusercontent.com',
    iosClientId: '258011664234-cv4pahmv0ra2t1v36b4omhl0821sjli3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulpoxAdmin',
  );
}
